### ISSUE TITLE
setColumn() on a non-object in Adminhtml/Block/Widget/Grid/Column.php on line 291

### ISSUE THREAD

**Issue by JonatanM** [jaimeneto85/sitemap-xml-generator#3]
Ola @jaimeneto85 quando acesso o admin no sitemap esta dando esse erro você teve esse erro ou sera que e com a minha instalação?

Fatal error: Call to a member function setColumn() on a non-object in ROOT/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column.php on line 291

Abraços

**Comment by jaimeneto85** [comment]
Oi, Jonatan.

Qual sua versão do magento?

Esse erro é num método padrão do próprio magento (como você pode ver pelo
próprio caminho).

--
*@jaimeneto85*

**Comment by JonatanM** [comment]
Achei o erro ainda bem que erra no seu modulo hahaha não queria instalar de novo o magento 

na linha 68 do arquivo Grid.php
esta assim 
'renderer' => 'buscapemap/admin_grid_renderer_link'

o correto seria asim ne?

'renderer' => 'Sitemaps_Block_Admin_Grid_Renderer_Link'

**Comment by JonatanM** [comment]
Pena que ainda pra min nao esta gerando os conteudo das tag :(

<product>
		<name></name>
		<price></price>
		<sku></sku>
		<url_path></url_path>
		<image></image>
		<stock></stock>
		<></>
	</product>

**Comment by JonatanM** [comment]
Log
2015-03-09T15:41:06+00:00 ERR (3): Deprecated functionality: Function split() is deprecated  in ROOT/app/code/local/Sitemaps/Model/Sitemap.php on line 169

**Comment by jaimeneto85** [comment]
Na verdade o principal problema estava no jQuery. Seu admin estava sem
jQuery. Coloquei uma instalação limpa do Magento e vi o mesmo erro. Veja
que para você só aparece uma coluna (tag), mas não a coluna "value".
- Adicionei o jQuery
- Coloquei um improvement de trabalhar com SimpleXML

Agora, ao salvar não exibe a lista de XMLs já salvos, mas isso corrijo
ainda hoje. Ao menos já dá para começar a trabalhar.

*Uma dica: *{{image}} gera o caminho da pasta (ex: /as/asa/image.jpg) para
uso externo você precisa do caminho completo. Para fazer isso, você pode
colocar http://seusite.com/media/{{image}} no campo valor

## 

_@jaimeneto85_

**Comment by jonatanaxe** [comment]
Quase funcionou pra mim :) quando vai gerando o xml antes de terminar e e da um erro.
Ele chega agerar 
a:5:{i:0;s:151:"Cannot send headers; headers already sent in ROOT/app/code/local/Sitemaps/Model/Sitemap.php(224) : eval()'d code, line 1";i:1;s:1283:"#0 ROOT/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 ROOT/app/code/core/Mage/Core/Controller/Response/Http.php(107): Zend_Controller_Response_Abstract->setRedirect('http://dev....', 302)
#2 ROOT/app/code/local/Sitemaps/controllers/SitemapsController.php(127): Mage_Core_Controller_Response_Http->setRedirect('http://dev....')
#3 ROOT/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Sitemaps_SitemapsController->genAction()
#4 ROOT/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('gen')
#5 ROOT/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 ROOT/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#7 ROOT/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 ROOT/index.php(87): Mage::run('', 'store')
#9 {main}";s:3:"url";s:67:"/index.php/admin/sitemaps/gen/key/f656b8d6bd0216266dcc7f2f42b92ac3/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

Log 2015-03-11T20:33:02+00:00 ERR (3): Deprecated functionality: Function split() is deprecated  in /var/www/vhosts/dev.ROOT.com/app/code/local/Sitemaps/Model/Sitemap.php on line 168
2015-03-11T20:33:02+00:00 ERR (3): Notice: Array to string conversion  in /var/www/vhosts/dev.ROOT.com/app/code/local/Sitemaps/Model/Sitemap.php on line 224
2015-03-11T20:33:39+00:00 ERR (3): Notice: Array to string conversion  in /var/www/vhosts/dev.ROOT.com/app/code/local/Sitemaps/Model/Sitemap.php on line 216

**Comment by pedrordesign** [comment]
To com o mesmo problema: (1.7.0.2 )
Depois de instalado o módulo o sitemaps da o erro:

Fatal error: Call to a member function setColumn() on a non-object in /home/USER/public_html/loja/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Column.php on line 291

Fiz o que o JonatanM falou de trocar a linha
'renderer' => 'buscapemap/admin_grid_renderer_link'

por

'renderer' => 'Sitemaps_Block_Admin_Grid_Renderer_Link'

e o erro parou, mas pel oque li não é o certo.. o que devo fazer?
